### ISSUE TITLE
CPS2: Mars Matrix music sounds too low + sound effects only on the left channel

### ISSUE THREAD

**Issue by thehughhefner** [jotego/jtcps1#118]
Hi,
Mars Matrix music sounds too low compared to other CPS2 games. I don't have the original board to compare, however, compared to other games on the same hardware it's low.

Also, the sound effects (shooting) seem only to appear on the left channel.

**Comment by jotego** [comment]
All CPS2 games share the same sound subsystem as far as I know. The game must have been programmed to be quiet. Feeling the sound to come only from one source may be due to the spatial nature of Q-Sound, you may try moving a bit. I can hear the shooting sound from both speakers if I move close to them.
