### ISSUE TITLE
Off black color surrounding background sprites/elements

### ISSUE THREAD

**Issue by protogem2** [jotego/jtcps1#52]
On certain games like Magic Sword background elements meant to be black are a lighter color, showing up against the background:

https://imgur.com/a/E5afM16

**Comment by jotego** [comment]
Thanks for reporting it here.
I think that subtle differences in tone were not visible in most monitors so it eluded the designers.
We can play with the brightness and gamma settings to make it go away.
I think it’s best to tackle this with gamma files in MiSTer rather than in the core itself.
Although, the way brightness is modelled could be changed to make the difference less noticeable.
Note that the same issue can be seen in MAME too where brightness is handled with lower resolution.
I'm closing it for now but at some point I may look back at this. Particularly when I start making the CPS2 games as some of the GFX hardware is common.
