### ISSUE TITLE
Missplaced pixels on Street Fighter 2's tittle logo.

### ISSUE THREAD

**Issue by PepAlacant** [jotego/jtcps1#80]
![9DE1024B-48E0-49CB-9228-2919FA4EE9BD](https://user-images.githubusercontent.com/75079781/106446640-c7772d80-6480-11eb-84dc-0e2d97b27940.png)

Just one or two pixels moved from their place. Happens in mist/mister. I didn't noticed the problem in other games by now.

![30620E48-26FD-4179-856A-0B32A2A72434](https://user-images.githubusercontent.com/75079781/106448364-f1c9ea80-6482-11eb-9fdb-f3888717bcef.jpeg)

It happens it the letter "I" and missplaced more pixels in the letter "E" in the japanese version of SF2 Turbo.

**Comment by jotego** [comment]
This is most likely a problem in the ROM file. I have seen this kind of problem in two other games. They are due to incorrect ROM dumps.

**Comment by ItsAtomico** [comment]
Similar issue in SFZCH:

![2525-screen](https://user-images.githubusercontent.com/69975383/106460456-27b2a300-6472-11eb-81f2-6034f093a028.png)
![2658-screen](https://user-images.githubusercontent.com/69975383/106460460-284b3980-6472-11eb-9f42-a472c2743d08.png)
![2921-screen](https://user-images.githubusercontent.com/69975383/106460462-28e3d000-6472-11eb-988e-f552f1ef2e1b.png)
![2334-screen](https://user-images.githubusercontent.com/69975383/106460466-297c6680-6472-11eb-9cb0-6543f2a61930.png)

Weirdly enough it only happens when Guy's standing on the left side of the screen. When he's on the right the sprite doesn't glitch.

**Comment by jotego** [comment]
Well spotted. I have caught the problem. I will release an update today.
