### ISSUE TITLE
cps 1.5 3º player

### ISSUE THREAD

**Issue by leosmendes** [jotego/jtcps1#92]
the core of cps1.5 working normally for 3 players? I ask why I can't get any buttons on "cadlac and dinosaurs" I managed to use 3 controls smoothly on the gauntlet core. I activated in the configuration part of the game 3 payers too. I can't get any response in the core of cps 1.5 from the third controller, even though I mapped it and activated it too

**Comment by jotego** [comment]
Hello, there is a problem with the third player input. I have already spent a couple of sessions debugging it but haven't found the culprit yet. 
I am taking this problem here

https://github.com/jotego/jtbin/issues/148

So I will close this thread. Thank you for reporting it. I will continue chasing this issue.
